[package]
name = "space_war_supreme"
version = "1.0.0"
authors = ["Raz Hemo"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
rand = "0.7.3"
lazy_static = "1.4.0"
rhai = "0.9.1"
image = "0.22.4"
winit = "0.20.0"
