[package]
name = "space_war_supreme"
version = "1.0.0"
authors = ["Raz Hemo"]
edition = "2018"
build = "build.rs"

[build-dependencies]
winres = "0.1.11"

[dependencies]
chrono = "0.4.10"
rand = "0.7.3"
lazy_static = "1.4.0"
rhai = "0.9.1"
image = "0.23.0"
winit = "0.21.0"
vulkano = "0.17.0"
vulkano-win = "0.17.0"
winres = "0.1.11"
msgbox = "0.4.0"
rodio = "0.10.0"

#[profile.release]
#lto = true